// lib/models/fete_modele.dart
class Fete {
  final int jour;
  final int mois;
  final String nom;
  final String description;
  final String type; // "fete", "solennite", "memoire", "temps"
  final String couleur; // couleur liturgique
  final String? saintDuJour;
  final String? imageUrl;

  Fete({
    required this.jour,
    required this.mois,
    required this.nom,
    required this.description,
    required this.type,
    required this.couleur,
    this.saintDuJour,
    this.imageUrl,
  });

  DateTime get date {
    final now = DateTime.now();
    return DateTime(now.year, mois, jour);
  }

  bool get estPasse {
    final now = DateTime.now();
    final dateFete = date;
    return now.isAfter(dateFete);
  }

  int get joursRestants {
    final now = DateTime.now();
    final dateFete = date;
    if (now.isAfter(dateFete)) {
      final anneeProchaine = now.year + 1;
      return DateTime(anneeProchaine, mois, jour).difference(now).inDays;
    }
    return dateFete.difference(now).inDays;
  }
}

class CalendrierLiturgiqueData {
  static List<Fete> toutesLesFetes = [

    // ══════════════════════════════════════════
    // JANVIER
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 1,
      nom: 'Sainte Marie, Mère de Dieu',
      description: 'Solennité de la Bienheureuse Vierge Marie, Mère de Dieu. Octave de Noël.',
      type: 'solennite',
      couleur: 'blanc',
      saintDuJour: 'Marie',
    ),
    Fete(
      jour: 2,
      mois: 1,
      nom: 'Saints Basile le Grand et Grégoire de Nazianze',
      description: 'Évêques et docteurs de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 1,
      nom: 'Très Saint Nom de Jésus',
      description: 'Mémoire facultative du Saint Nom de Jésus.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 1,
      nom: 'Sainte Élisabeth Ann Seton',
      description: 'Religieuse américaine, fondatrice des Sœurs de la Charité.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 1,
      nom: 'Saint Jean Neumann',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 1,
      nom: 'Épiphanie du Seigneur',
      description: 'Solennité de la manifestation de Jésus aux nations.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 1,
      nom: 'Saint Raymond de Peñafort',
      description: 'Prêtre et confesseur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 1,
      nom: 'Saint Apollinaire le Jeune',
      description: 'Évêque de Ravenne.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 1,
      nom: 'Saint Julien de Tolède',
      description: 'Évêque et docteur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 1,
      nom: 'Saint Guillaume de Bourges',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 1,
      nom: 'Saint Hygin',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 12,
      mois: 1,
      nom: 'Saint Tatien',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 13,
      mois: 1,
      nom: 'Saint Hilaire de Poitiers',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 1,
      nom: 'Saint Félix de Nole',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 1,
      nom: 'Saint Paul Ermite',
      description: 'Premier ermite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 1,
      nom: 'Saint Marcel Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 17,
      mois: 1,
      nom: 'Saint Antoine le Grand',
      description: 'Abbé, père des moines.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 1,
      nom: 'Sainte Prisque',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 1,
      nom: 'Saint Canut',
      description: 'Roi et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 20,
      mois: 1,
      nom: 'Saint Sébastien',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 21,
      mois: 1,
      nom: 'Sainte Agnès',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 22,
      mois: 1,
      nom: 'Saint Vincent',
      description: 'Diacre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 1,
      nom: 'Saint Ildefonse',
      description: 'Évêque de Tolède.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 1,
      nom: 'Saint François de Sales',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 1,
      nom: 'Conversion de Saint Paul',
      description: 'Fête de la conversion de l\'Apôtre des nations.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 1,
      nom: 'Saints Timothée et Tite',
      description: 'Évêques, compagnons de Saint Paul.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 1,
      nom: 'Sainte Angèle Mérici',
      description: 'Vierge, fondatrice des Ursulines.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 1,
      nom: 'Saint Thomas d\'Aquin',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 1,
      nom: 'Saint Sulpice',
      description: 'Évêque de Bourges.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 1,
      nom: 'Sainte Martine',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 31,
      mois: 1,
      nom: 'Saint Jean Bosco',
      description: 'Prêtre, fondateur des Salésiens.',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // FÉVRIER
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 2,
      nom: 'Sainte Brigitte d\'Irlande',
      description: 'Abbesse, patronne de l\'Irlande.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 2,
      nom: 'Présentation du Seigneur',
      description: 'Fête de la Présentation de Jésus au Temple. Chandeleur.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 2,
      nom: 'Saint Blaise',
      description: 'Évêque et martyr. Bénédiction des gorges.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 4,
      mois: 2,
      nom: 'Saint Jean de Brito',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 5,
      mois: 2,
      nom: 'Sainte Agathe',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 6,
      mois: 2,
      nom: 'Saint Paul Miki et ses compagnons',
      description: 'Martyrs du Japon.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 7,
      mois: 2,
      nom: 'Saint Richard de Wyche',
      description: 'Évêque de Chichester.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 2,
      nom: 'Sainte Joséphine Bakhita',
      description: 'Vierge, soudanaise.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 2,
      nom: 'Sainte Apollonie',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 10,
      mois: 2,
      nom: 'Sainte Scholastique',
      description: 'Vierge, sœur de Saint Benoît.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 2,
      nom: 'Notre-Dame de Lourdes',
      description: 'Apparitions de la Vierge à Bernadette.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 2,
      nom: 'Sept Saints Fondateurs des Servites de Marie',
      description: 'Religieux.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 2,
      nom: 'Sainte Catherine de Ricci',
      description: 'Vierge dominicaine.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 2,
      nom: 'Saint Valentin',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 2,
      nom: 'Saint Faustin',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 16,
      mois: 2,
      nom: 'Saint Onésime',
      description: 'Martyr, disciple de saint Paul.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 17,
      mois: 2,
      nom: 'Sept Saints Fondateurs de l\'Ordre des Servites',
      description: 'Religieux fondateurs.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 2,
      nom: 'Sainte Bernadette Soubirous',
      description: 'Vierge, voyante de Lourdes.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 2,
      nom: 'Saint Conrad de Plaisance',
      description: 'Ermite franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 2,
      nom: 'Bienheureux Jacinto et Francisco Marto',
      description: 'Voyants de Fatima.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 2,
      nom: 'Saint Pierre Damien',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 2,
      nom: 'Chaire de Saint Pierre',
      description: 'Fête de la mission de Pierre dans l\'Église.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 2,
      nom: 'Saint Polycarpe',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 24,
      mois: 2,
      nom: 'Saint Étienne Ier de Hongrie',
      description: 'Roi.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 2,
      nom: 'Saint Walburge',
      description: 'Abbesse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 2,
      nom: 'Saint Alexandre',
      description: 'Patriarche d\'Alexandrie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 2,
      nom: 'Saint Gabriel de Notre-Dame des Douleurs',
      description: 'Religieux passioniste.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 2,
      nom: 'Saint Romain',
      description: 'Abbé fondateur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 2,
      nom: 'Saint Oswald de Worcester',
      description: 'Évêque (année bissextile).',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // MARS
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 3,
      nom: 'Saint David de Galles',
      description: 'Évêque, patron du Pays de Galles.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 3,
      nom: 'Saint Simplice',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 3,
      nom: 'Sainte Cunégonde',
      description: 'Impératrice.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 3,
      nom: 'Saint Casimir',
      description: 'Prince, confesseur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 3,
      nom: 'Saint Jean-Joseph de la Croix',
      description: 'Prêtre franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 3,
      nom: 'Sainte Colette',
      description: 'Vierge réformatrice des Clarisses.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 3,
      nom: 'Saintes Perpétue et Félicité',
      description: 'Martyres à Carthage.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 8,
      mois: 3,
      nom: 'Saint Jean de Dieu',
      description: 'Religieux, fondateur des Frères de la Charité.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 3,
      nom: 'Sainte Françoise Romaine',
      description: 'Veuve, religieuse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 3,
      nom: 'Saint Macaire de Jérusalem',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 3,
      nom: 'Saint Sophrone de Jérusalem',
      description: 'Patriarche.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 3,
      nom: 'Saint Grégoire le Grand',
      description: 'Pape et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 3,
      nom: 'Saint Rodrigue',
      description: 'Martyr de Cordoue.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 14,
      mois: 3,
      nom: 'Sainte Mathilde',
      description: 'Reine.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 15,
      mois: 3,
      nom: 'Saint Longin',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 16,
      mois: 3,
      nom: 'Saint Julien de Antioche',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 17,
      mois: 3,
      nom: 'Saint Patrick',
      description: 'Évêque, apôtre de l\'Irlande.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 3,
      nom: 'Saint Cyrille de Jérusalem',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 3,
      nom: 'Saint Joseph, époux de la Vierge Marie',
      description: 'Solennité de Saint Joseph, patron de l\'Église universelle.',
      type: 'solennite',
      couleur: 'blanc',
      saintDuJour: 'Joseph',
      imageUrl: 'assets/images/st_joseph.jpg',
    ),
    Fete(
      jour: 20,
      mois: 3,
      nom: 'Saint Herbert',
      description: 'Ermite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 3,
      nom: 'Saint Benoît de Nursie',
      description: 'Abbé, fondateur du monachisme occidental.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 3,
      nom: 'Saint Nicolas Owen',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 3,
      nom: 'Saint Turibio de Mogrovejo',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 3,
      nom: 'Saint Gabriel Archange',
      description: 'Archange messager.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 3,
      nom: 'Annonciation du Seigneur',
      description: 'Solennité de l\'Annonciation faite à Marie.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 3,
      nom: 'Saint Ludger',
      description: 'Évêque de Munster.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 3,
      nom: 'Saint Rupert',
      description: 'Évêque de Salzbourg.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 3,
      nom: 'Saint Gontran',
      description: 'Roi des Francs.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 3,
      nom: 'Saint Cyriaque',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 30,
      mois: 3,
      nom: 'Saint Jean Climaque',
      description: 'Abbé du Sinaï.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 3,
      nom: 'Sainte Balbine',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),

    // ══════════════════════════════════════════
    // AVRIL
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 4,
      nom: 'Saint Hugues de Grenoble',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 4,
      nom: 'Saint François de Paule',
      description: 'Ermite, fondateur des Minimes.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 4,
      nom: 'Saint Richard de Chichester',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 4,
      nom: 'Saint Isidore de Séville',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 4,
      nom: 'Saint Vincent Ferrier',
      description: 'Prêtre dominicain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 4,
      nom: 'Saint Sixte Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 7,
      mois: 4,
      nom: 'Saint Jean-Baptiste de la Salle',
      description: 'Prêtre, fondateur des Frères des Écoles Chrétiennes.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 4,
      nom: 'Saint Walter',
      description: 'Abbé.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 4,
      nom: 'Sainte Marie Cléophas',
      description: 'Disciple du Christ.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 4,
      nom: 'Saint Ezéchiel',
      description: 'Prophète.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 4,
      nom: 'Saint Stanislas',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 12,
      mois: 4,
      nom: 'Saint Zénon de Vérone',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 4,
      nom: 'Saint Martin Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 14,
      mois: 4,
      nom: 'Saint Tiburce',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 4,
      nom: 'Sainte Anastasie',
      description: 'Martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 16,
      mois: 4,
      nom: 'Sainte Bernadette',
      description: 'Vierge, voyante de Lourdes.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 4,
      nom: 'Saint Anicet',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 18,
      mois: 4,
      nom: 'Saint Apollone',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 4,
      nom: 'Saint Léon IX',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 4,
      nom: 'Sainte Agnès de Montepulciano',
      description: 'Vierge dominicaine.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 4,
      nom: 'Saint Anselme',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 4,
      nom: 'Saint Sotère',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 4,
      nom: 'Saint Georges',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 24,
      mois: 4,
      nom: 'Saint Fidèle de Sigmaringen',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 25,
      mois: 4,
      nom: 'Saint Marc',
      description: 'Évangéliste.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 26,
      mois: 4,
      nom: 'Notre-Dame du Bon Conseil',
      description: 'Mémoire de la Vierge du Bon Conseil.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 4,
      nom: 'Saint Zite',
      description: 'Vierge.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 4,
      nom: 'Saint Pierre Chanel',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 4,
      nom: 'Sainte Catherine de Sienne',
      description: 'Vierge et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 4,
      nom: 'Saint Pie V',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // MAI
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 5,
      nom: 'Saint Joseph travailleur',
      description: 'Mémoire de Saint Joseph travailleur, protecteur des travailleurs.',
      type: 'memoire',
      couleur: 'blanc',
      saintDuJour: 'Joseph',
      imageUrl: 'assets/images/st_joseph_travailleur.jpg',
    ),
    Fete(
      jour: 2,
      mois: 5,
      nom: 'Saint Athanase',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 5,
      nom: 'Saints Philippe et Jacques',
      description: 'Apôtres.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 4,
      mois: 5,
      nom: 'Saint Florian',
      description: 'Martyr, patron des pompiers.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 5,
      mois: 5,
      nom: 'Saint Ange',
      description: 'Prêtre et martyr carme.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 6,
      mois: 5,
      nom: 'Saint Jean Devant la Porte Latine',
      description: 'Fête de Saint Jean apôtre.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 5,
      nom: 'Saint Stanislas Kazimierczyk',
      description: 'Prêtre.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 5,
      nom: 'Apparition de Saint Michel Archange',
      description: 'Dédicace du sanctuaire du Mont-Gargan.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 5,
      nom: 'Saint Pakhôme',
      description: 'Abbé, fondateur du monachisme cénobitique.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 5,
      nom: 'Saint Jean d\'Avila',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 5,
      nom: 'Bienheureux Ignace de Laconi',
      description: 'Frère capucin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 5,
      nom: 'Saints Nérée et Achillée',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 13,
      mois: 5,
      nom: 'Notre-Dame de Fatima',
      description: 'Apparitions de la Vierge à Fatima.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 5,
      nom: 'Saint Matthias',
      description: 'Apôtre.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 5,
      nom: 'Saint Isidore le Laboureur',
      description: 'Agriculteur, patron des paysans.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 5,
      nom: 'Saint Simon Stock',
      description: 'Religieux carme.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 5,
      nom: 'Saint Pascal Baylon',
      description: 'Religieux franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 5,
      nom: 'Saint Jean Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 5,
      nom: 'Saint Yves',
      description: 'Prêtre, patron des avocats.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 5,
      nom: 'Saint Bernardin de Sienne',
      description: 'Prêtre.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 5,
      nom: 'Saint Christophe Magallanes',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 22,
      mois: 5,
      nom: 'Sainte Rita de Cascia',
      description: 'Veuve, religieuse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 5,
      nom: 'Saint Jean-Baptiste Rossi',
      description: 'Prêtre romain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 5,
      nom: 'Notre-Dame Auxiliatrice',
      description: 'Mémoire de la Vierge Auxiliatrice.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 5,
      nom: 'Saint Bède le Vénérable',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 5,
      nom: 'Saint Philippe Néri',
      description: 'Prêtre, fondateur de l\'Oratoire.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 5,
      nom: 'Saint Augustin de Cantorbéry',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 5,
      nom: 'Saint Germain de Paris',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 5,
      nom: 'Sainte Ursule Ledóchowska',
      description: 'Vierge et fondatrice.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 5,
      nom: 'Sainte Jeanne d\'Arc',
      description: 'Vierge, patronne de la France.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 5,
      nom: 'Visitation de la Vierge Marie',
      description: 'Fête de la Visitation de Marie à Élisabeth.',
      type: 'fete',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // JUIN
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 6,
      nom: 'Saint Justin',
      description: 'Philosophe et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 2,
      mois: 6,
      nom: 'Saints Marcellin et Pierre',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 3,
      mois: 6,
      nom: 'Saint Charles Lwanga et compagnons',
      description: 'Martyrs de l\'Ouganda.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 4,
      mois: 6,
      nom: 'Saint François Caracciolo',
      description: 'Prêtre, fondateur des Clercs Réguliers Mineurs.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 6,
      nom: 'Saint Boniface',
      description: 'Évêque et martyr, apôtre de la Germanie.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 6,
      mois: 6,
      nom: 'Saint Norbert',
      description: 'Évêque, fondateur des Prémontrés.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 6,
      nom: 'Sacré-Cœur de Jésus',
      description: 'Solennité du Sacré-Cœur de Jésus (date variable).',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 6,
      nom: 'Cœur Immaculé de Marie',
      description: 'Mémoire du Cœur Immaculé de Marie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 6,
      nom: 'Saint Éphrem',
      description: 'Diacre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 6,
      nom: 'Bienheureux Henri de Suède',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 11,
      mois: 6,
      nom: 'Saint Barnabé',
      description: 'Apôtre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 12,
      mois: 6,
      nom: 'Saint Jean de Sahagun',
      description: 'Prêtre augustin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 6,
      nom: 'Saint Antoine de Padoue',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 6,
      nom: 'Saint Elisée',
      description: 'Prophète.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 15,
      mois: 6,
      nom: 'Saint Vite',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 16,
      mois: 6,
      nom: 'Saint Quirique et Juliette',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 17,
      mois: 6,
      nom: 'Saint Grégoire Barbarigo',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 6,
      nom: 'Saint Éphrem le Syrien',
      description: 'Diacre et docteur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 6,
      nom: 'Saint Romuald',
      description: 'Abbé, fondateur des Camaldules.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 6,
      nom: 'Saint Silverius',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 21,
      mois: 6,
      nom: 'Saint Louis de Gonzague',
      description: 'Religieux jésuite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 6,
      nom: 'Saint Paulin de Nole',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 6,
      nom: 'Sainte Audrey',
      description: 'Abbesse, reine d\'Angleterre.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 6,
      nom: 'Nativité de Saint Jean-Baptiste',
      description: 'Solennité de la naissance du Précurseur.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 6,
      nom: 'Saint Prosper d\'Aquitaine',
      description: 'Écrivain ecclésiastique.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 6,
      nom: 'Saint Josémaria Escriva',
      description: 'Prêtre, fondateur de l\'Opus Dei.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 6,
      nom: 'Saint Cyrille d\'Alexandrie',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 6,
      nom: 'Saint Irénée',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 6,
      nom: 'Saints Pierre et Paul',
      description: 'Apôtres, solennité.',
      type: 'solennite',
      couleur: 'rouge',
    ),
    Fete(
      jour: 30,
      mois: 6,
      nom: 'Premiers martyrs de Rome',
      description: 'Martyrs sous Néron.',
      type: 'memoire',
      couleur: 'rouge',
    ),

    // ══════════════════════════════════════════
    // JUILLET
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 7,
      nom: 'Saint Thierry',
      description: 'Abbé.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 7,
      nom: 'Saint Bernardin de Réalino',
      description: 'Prêtre jésuite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 7,
      nom: 'Saint Thomas',
      description: 'Apôtre.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 4,
      mois: 7,
      nom: 'Sainte Élisabeth de Portugal',
      description: 'Reine, pacificatrice.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 7,
      nom: 'Saint Antoine Marie Zaccaria',
      description: 'Prêtre, fondateur des Barnabites.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 7,
      nom: 'Sainte Maria Goretti',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 7,
      mois: 7,
      nom: 'Saints Augustins Zhao Rong et compagnons',
      description: 'Martyrs de Chine.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 8,
      mois: 7,
      nom: 'Sainte Priscille',
      description: 'Disciple de Saint Paul.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 7,
      nom: 'Saint Augustin Zhao Rong',
      description: 'Martyrs de Chine.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 10,
      mois: 7,
      nom: 'Saint Rufin',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 11,
      mois: 7,
      nom: 'Saint Benoît',
      description: 'Abbé, père du monachisme occidental, patron de l\'Europe.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 7,
      nom: 'Saints Nabor et Félix',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 13,
      mois: 7,
      nom: 'Saint Henri',
      description: 'Empereur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 7,
      nom: 'Saint Camille de Lellis',
      description: 'Prêtre, fondateur des Camilliens.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 15,
      mois: 7,
      nom: 'Saint Bonaventure',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 7,
      nom: 'Notre-Dame du Mont-Carmel',
      description: 'Mémoire de la Bienheureuse Vierge Marie du Mont-Carmel.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 7,
      nom: 'Bienheureuses vierges et martyres de Compiègne',
      description: 'Carmélites martyres de la Révolution française.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 18,
      mois: 7,
      nom: 'Saint Frédéric de Utrecht',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 7,
      nom: 'Saint Arsène',
      description: 'Diacre, ermite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 7,
      nom: 'Saint Apollinaire',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 21,
      mois: 7,
      nom: 'Saint Laurent de Brindisi',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 7,
      nom: 'Sainte Marie Madeleine',
      description: 'Apôtre des apôtres.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 7,
      nom: 'Sainte Brigitte de Suède',
      description: 'Religieuse, patronne de l\'Europe.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 7,
      nom: 'Saint Charbel Makhlouf',
      description: 'Prêtre, ermite libanais.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 7,
      nom: 'Saint Jacques',
      description: 'Apôtre.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 26,
      mois: 7,
      nom: 'Saints Joachim et Anne',
      description: 'Parents de la Vierge Marie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 7,
      nom: 'Saint Pantaleón',
      description: 'Médecin et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 28,
      mois: 7,
      nom: 'Saints Nazaire et Celse',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 7,
      nom: 'Sainte Marthe, Marie et Lazare',
      description: 'Amis du Seigneur à Béthanie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 7,
      nom: 'Saint Pierre Chrysologue',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 7,
      nom: 'Saint Ignace de Loyola',
      description: 'Prêtre, fondateur des Jésuites.',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // AOÛT
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 8,
      nom: 'Saint Alphonse de Liguori',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 8,
      nom: 'Saint Eusèbe de Verceil',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 8,
      nom: 'Saint Étienne Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 4,
      mois: 8,
      nom: 'Saint Jean-Marie Vianney',
      description: 'Curé d\'Ars, saint patron des curés.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 8,
      nom: 'Dédicace de Sainte-Marie-Majeure',
      description: 'Mémoire de la basilique Sainte-Marie-Majeure.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 8,
      nom: 'Transfiguration du Seigneur',
      description: 'Fête de la Transfiguration.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 8,
      nom: 'Saint Sixte II et compagnons',
      description: 'Pape et martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 8,
      mois: 8,
      nom: 'Saint Dominique',
      description: 'Prêtre, fondateur des Dominicains.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 8,
      nom: 'Sainte Thérèse Bénédicte de la Croix (Edith Stein)',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 10,
      mois: 8,
      nom: 'Saint Laurent',
      description: 'Diacre et martyr.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 11,
      mois: 8,
      nom: 'Sainte Claire',
      description: 'Vierge, fondatrice des Clarisses.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 8,
      nom: 'Sainte Jeanne Françoise de Chantal',
      description: 'Religieuse, fondatrice de la Visitation.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 8,
      nom: 'Saints Pontien et Hippolyte',
      description: 'Martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 14,
      mois: 8,
      nom: 'Saint Maximilien Kolbe',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 8,
      nom: 'Assomption de la Vierge Marie',
      description: 'Solennité de l\'Assomption.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 8,
      nom: 'Saint Étienne de Hongrie',
      description: 'Roi.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 8,
      nom: 'Saint Hyacinthe',
      description: 'Prêtre dominicain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 8,
      nom: 'Sainte Hélène',
      description: 'Impératrice, mère de Constantin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 8,
      nom: 'Saint Jean Eudes',
      description: 'Prêtre, apôtre des Cœurs de Jésus et Marie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 8,
      nom: 'Saint Bernard',
      description: 'Abbé et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 8,
      nom: 'Saint Pie X',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 8,
      nom: 'Vierge Marie Reine',
      description: 'Mémoire de la Sainte Vierge Marie Reine.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 8,
      nom: 'Sainte Rose de Lima',
      description: 'Vierge, première sainte des Amériques.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 8,
      nom: 'Saint Barthélemy',
      description: 'Apôtre.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 25,
      mois: 8,
      nom: 'Saint Louis',
      description: 'Roi de France.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 8,
      nom: 'Sainte Zéphyrin',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 27,
      mois: 8,
      nom: 'Sainte Monique',
      description: 'Mère de Saint Augustin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 8,
      nom: 'Saint Augustin',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 8,
      nom: 'Martyre de Saint Jean-Baptiste',
      description: 'Mémoire de la décollation de Saint Jean-Baptiste.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 30,
      mois: 8,
      nom: 'Sainte Rose de Lima',
      description: 'Vierge.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 8,
      nom: 'Saint Raymond Nonnat',
      description: 'Cardinal, religieux mercédaire.',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // SEPTEMBRE
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 9,
      nom: 'Saint Gilles',
      description: 'Abbé.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 9,
      nom: 'Saint Étienne de Hongrie',
      description: 'Roi fondateur de la Hongrie chrétienne.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 9,
      nom: 'Saint Grégoire le Grand',
      description: 'Pape et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 9,
      nom: 'Sainte Rosalie',
      description: 'Vierge, patronne de Palerme.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 9,
      nom: 'Sainte Mère Teresa de Calcutta',
      description: 'Vierge, fondatrice des Missionnaires de la Charité.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 9,
      nom: 'Bienheureux Bertrand de Garrigues',
      description: 'Prêtre dominicain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 9,
      nom: 'Saint Cloud',
      description: 'Petit-fils de Clovis, ermite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 9,
      nom: 'Nativité de la Vierge Marie',
      description: 'Fête de la Nativité de Marie.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 9,
      nom: 'Saint Pierre Claver',
      description: 'Prêtre, apôtre des esclaves.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 9,
      nom: 'Saint Nicolas de Tolentin',
      description: 'Prêtre augustin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 9,
      nom: 'Saint Hyacinthe',
      description: 'Martyr de Rome.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 12,
      mois: 9,
      nom: 'Saint Nom de Marie',
      description: 'Mémoire du Très Saint Nom de Marie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 9,
      nom: 'Saint Jean Chrysostome',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 9,
      nom: 'Exaltation de la Sainte Croix',
      description: 'Fête de la Croix glorieuse.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 9,
      nom: 'Notre-Dame des Douleurs',
      description: 'Mémoire de la Vierge des Douleurs.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 9,
      nom: 'Saints Corneille et Cyprien',
      description: 'Pape et évêque, martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 17,
      mois: 9,
      nom: 'Saint Robert Bellarmin',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 9,
      nom: 'Saint Joseph de Copertino',
      description: 'Prêtre franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 9,
      nom: 'Saint Janvier',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 20,
      mois: 9,
      nom: 'Saints André Kim Taegon et Paul Chong Hasang',
      description: 'Martyrs de Corée.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 21,
      mois: 9,
      nom: 'Saint Matthieu',
      description: 'Apôtre et évangéliste.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 22,
      mois: 9,
      nom: 'Saint Maurice et compagnons',
      description: 'Martyrs de la légion thébaine.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 9,
      nom: 'Saint Pie de Pietrelcina (Padre Pio)',
      description: 'Prêtre capucin, stigmatisé.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 9,
      nom: 'Notre-Dame de la Merci',
      description: 'Mémoire de Notre-Dame de la Miséricorde.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 9,
      nom: 'Saint Cléophas',
      description: 'Disciple d\'Emmaüs.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 9,
      nom: 'Saints Côme et Damien',
      description: 'Médecins et martyrs.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 27,
      mois: 9,
      nom: 'Saint Vincent de Paul',
      description: 'Prêtre, fondateur des Lazaristes et des Filles de la Charité.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 9,
      nom: 'Saint Wenceslas',
      description: 'Martyr, patron de la Bohême.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 9,
      nom: 'Saints Michel, Gabriel et Raphaël',
      description: 'Archanges.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 9,
      nom: 'Saint Jérôme',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),

    // ══════════════════════════════════════════
    // OCTOBRE
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 10,
      nom: 'Sainte Thérèse de l\'Enfant-Jésus',
      description: 'Vierge et docteur de l\'Église, patronne des missions.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 10,
      nom: 'Saints Anges Gardiens',
      description: 'Mémoire des Saints Anges Gardiens.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 3,
      mois: 10,
      nom: 'Saint Thomas de Hereford',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 10,
      nom: 'Saint François d\'Assise',
      description: 'Fondateur des Franciscains, patron de l\'écologie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 10,
      nom: 'Sainte Faustine Kowalska',
      description: 'Vierge, apôtre de la Divine Miséricorde.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 10,
      nom: 'Saint Bruno',
      description: 'Fondateur des Chartreux.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 10,
      nom: 'Notre-Dame du Rosaire',
      description: 'Mémoire de la Sainte Vierge du Rosaire.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 10,
      nom: 'Saint Siméon le Vieux',
      description: 'Père de Dieu.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 10,
      nom: 'Saint Denis et compagnons',
      description: 'Évêque et martyrs de Paris.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 10,
      mois: 10,
      nom: 'Saint Daniel le Stylite',
      description: 'Moine ascète.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 10,
      nom: 'Saint Jean XXIII',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 10,
      nom: 'Notre-Dame du Pilier',
      description: 'Mémoire de Notre-Dame de Saragosse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 10,
      nom: 'Saint Édouard le Confesseur',
      description: 'Roi d\'Angleterre.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 10,
      nom: 'Saint Callixte Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 10,
      nom: 'Sainte Thérèse d\'Avila',
      description: 'Vierge et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 10,
      nom: 'Sainte Marguerite Marie Alacoque',
      description: 'Vierge, apôtre du Sacré-Cœur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 10,
      nom: 'Saint Ignace d\'Antioche',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 18,
      mois: 10,
      nom: 'Saint Luc',
      description: 'Évangéliste.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 10,
      nom: 'Saints Jean de Brébeuf, Isaac Jogues et compagnons',
      description: 'Martyrs du Canada et des États-Unis.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 20,
      mois: 10,
      nom: 'Saint Paul de la Croix',
      description: 'Prêtre, fondateur des Passionistes.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 10,
      nom: 'Sainte Céline',
      description: 'Veuve.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 10,
      nom: 'Saint Jean-Paul II',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 23,
      mois: 10,
      nom: 'Saint Jean de Capistran',
      description: 'Prêtre franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 10,
      nom: 'Saint Antoine-Marie Claret',
      description: 'Évêque, fondateur des Claretains.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 25,
      mois: 10,
      nom: 'Saints Crépin et Crépinien',
      description: 'Martyrs, patrons des cordonniers.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 26,
      mois: 10,
      nom: 'Saint Dimitri',
      description: 'Grand-duc de Russie.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 10,
      nom: 'Bienheureux Bartholomée Gutiérrez',
      description: 'Prêtre et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 28,
      mois: 10,
      nom: 'Saints Simon et Jude',
      description: 'Apôtres.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 10,
      nom: 'Saint Narcisse de Jérusalem',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 30,
      mois: 10,
      nom: 'Saint Alphonse Rodriguez',
      description: 'Religieux jésuite.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 10,
      nom: 'Vigile de la Toussaint',
      description: 'Veille de la Solennité de tous les saints.',
      type: 'temps',
      couleur: 'violet',
    ),

    // ══════════════════════════════════════════
    // NOVEMBRE
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 11,
      nom: 'Toussaint',
      description: 'Solennité de tous les saints.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 11,
      nom: 'Commémoration des fidèles défunts',
      description: 'Jour des morts. Prière pour les âmes du Purgatoire.',
      type: 'memoire',
      couleur: 'violet',
    ),
    Fete(
      jour: 3,
      mois: 11,
      nom: 'Saint Martin de Porrès',
      description: 'Religieux dominicain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 11,
      nom: 'Saint Charles Borromée',
      description: 'Évêque de Milan, réformateur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 11,
      nom: 'Saint Zacharie et Sainte Élisabeth',
      description: 'Parents de Saint Jean-Baptiste.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 11,
      nom: 'Saint Léonard de Noblat',
      description: 'Ermite, patron des prisonniers.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 11,
      nom: 'Saint Willibrord',
      description: 'Évêque, apôtre de la Frise.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 11,
      nom: 'Bienheureux Jean Duns Scot',
      description: 'Prêtre et docteur.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 11,
      nom: 'Dédicace de la Basilique du Latran',
      description: 'Fête de la dédicace de la cathédrale du pape.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 11,
      nom: 'Saint Léon le Grand',
      description: 'Pape et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 11,
      nom: 'Saint Martin de Tours',
      description: 'Évêque, apôtre des Gaules.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 11,
      nom: 'Saint Josaphat',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 13,
      mois: 11,
      nom: 'Saint Didace (Diego) d\'Alcalá',
      description: 'Frère franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 14,
      mois: 11,
      nom: 'Saint Nikolaos Tavelic',
      description: 'Martyr franciscain.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 15,
      mois: 11,
      nom: 'Saint Albert le Grand',
      description: 'Évêque et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 11,
      nom: 'Sainte Marguerite d\'Écosse',
      description: 'Reine d\'Écosse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 11,
      nom: 'Sainte Élisabeth de Hongrie',
      description: 'Religieuse, patronne des Tertiaires franciscains.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 11,
      nom: 'Dédicace des basiliques de Pierre et Paul',
      description: 'Mémoire de la dédicace des deux grandes basiliques romaines.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 19,
      mois: 11,
      nom: 'Saint Abdias',
      description: 'Prophète.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 11,
      nom: 'Saint Félix de Valois',
      description: 'Prêtre, cofondateur de l\'Ordre de la Trinité.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 11,
      nom: 'Présentation de Marie',
      description: 'Mémoire de la Présentation de Marie au Temple.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 11,
      nom: 'Sainte Cécile',
      description: 'Vierge et martyre, patronne des musiciens.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 11,
      nom: 'Saint Clément Ier',
      description: 'Pape et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 24,
      mois: 11,
      nom: 'Saint André Dung-Lac et compagnons',
      description: 'Martyrs du Vietnam.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 25,
      mois: 11,
      nom: 'Sainte Catherine d\'Alexandrie',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 26,
      mois: 11,
      nom: 'Saint Conrad de Constance',
      description: 'Évêque.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 27,
      mois: 11,
      nom: 'Saint Virgile de Salzbourg',
      description: 'Évêque missionnaire.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 11,
      nom: 'Saint Jacques de la Marche',
      description: 'Prêtre franciscain.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 29,
      mois: 11,
      nom: 'Saint Saturnin',
      description: 'Évêque de Toulouse et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 30,
      mois: 11,
      nom: 'Saint André',
      description: 'Apôtre, frère de Pierre.',
      type: 'fete',
      couleur: 'rouge',
    ),

    // ══════════════════════════════════════════
    // DÉCEMBRE
    // ══════════════════════════════════════════
    Fete(
      jour: 1,
      mois: 12,
      nom: 'Saint Éloi',
      description: 'Évêque de Noyon, patron des orfèvres.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 2,
      mois: 12,
      nom: 'Sainte Bibiane',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 3,
      mois: 12,
      nom: 'Saint François Xavier',
      description: 'Prêtre jésuite, grand missionnaire.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 4,
      mois: 12,
      nom: 'Saint Jean Damascène',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 5,
      mois: 12,
      nom: 'Saint Sabbas',
      description: 'Abbé, fondateur de la laure de Mar Saba.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 6,
      mois: 12,
      nom: 'Saint Nicolas',
      description: 'Évêque de Myre, patron des enfants.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 7,
      mois: 12,
      nom: 'Saint Ambroise',
      description: 'Évêque de Milan et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 8,
      mois: 12,
      nom: 'Immaculée Conception',
      description: 'Solennité de l\'Immaculée Conception de Marie.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 9,
      mois: 12,
      nom: 'Saint Juan Diego',
      description: 'Voyant de Notre-Dame de Guadalupe.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 10,
      mois: 12,
      nom: 'Notre-Dame de Lorette',
      description: 'Mémoire de la Vierge de Lorette.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 11,
      mois: 12,
      nom: 'Saint Damase Ier',
      description: 'Pape.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 12,
      mois: 12,
      nom: 'Notre-Dame de Guadalupe',
      description: 'Fête de Notre-Dame de Guadalupe, patronne des Amériques.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 13,
      mois: 12,
      nom: 'Sainte Lucie',
      description: 'Vierge et martyre.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 14,
      mois: 12,
      nom: 'Saint Jean de la Croix',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 15,
      mois: 12,
      nom: 'Saint Ninien',
      description: 'Évêque, apôtre d\'Écosse.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 16,
      mois: 12,
      nom: 'Sainte Adélaïde',
      description: 'Impératrice.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 17,
      mois: 12,
      nom: 'Saint Lazare',
      description: 'Ami du Seigneur, premier évêque de Marseille.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 18,
      mois: 12,
      nom: 'Saint Flavien de Constantinople',
      description: 'Évêque et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 19,
      mois: 12,
      nom: 'Saint Urbain V',
      description: 'Pape bienheureux.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 20,
      mois: 12,
      nom: 'Saint Abraham',
      description: 'Patriarche.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 21,
      mois: 12,
      nom: 'Saint Pierre Canisius',
      description: 'Prêtre et docteur de l\'Église.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 22,
      mois: 12,
      nom: 'Saint Zénon',
      description: 'Martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 23,
      mois: 12,
      nom: 'Saint Jean de Kenty',
      description: 'Prêtre polonais.',
      type: 'memoire',
      couleur: 'blanc',
    ),
    Fete(
      jour: 24,
      mois: 12,
      nom: 'Vigile de Noël',
      description: 'Veille de la Nativité du Seigneur.',
      type: 'temps',
      couleur: 'violet',
    ),
    Fete(
      jour: 25,
      mois: 12,
      nom: 'Noël – Nativité du Seigneur',
      description: 'Solennité de la Nativité du Seigneur Jésus-Christ.',
      type: 'solennite',
      couleur: 'blanc',
    ),
    Fete(
      jour: 26,
      mois: 12,
      nom: 'Saint Étienne',
      description: 'Premier martyr (protomartyr).',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 27,
      mois: 12,
      nom: 'Saint Jean',
      description: 'Apôtre et évangéliste.',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 28,
      mois: 12,
      nom: 'Saints Innocents',
      description: 'Martyrs massacrés par Hérode.',
      type: 'fete',
      couleur: 'rouge',
    ),
    Fete(
      jour: 29,
      mois: 12,
      nom: 'Saint Thomas Becket',
      description: 'Évêque de Cantorbéry et martyr.',
      type: 'memoire',
      couleur: 'rouge',
    ),
    Fete(
      jour: 30,
      mois: 12,
      nom: 'Sainte Famille de Jésus, Marie et Joseph',
      description: 'Fête de la Sainte Famille (dimanche dans l\'octave de Noël).',
      type: 'fete',
      couleur: 'blanc',
    ),
    Fete(
      jour: 31,
      mois: 12,
      nom: 'Saint Sylvestre Ier',
      description: 'Pape, contemporain de Constantin.',
      type: 'memoire',
      couleur: 'blanc',
    ),
  ];

  static List<Fete> getFetesDuJour(DateTime date) {
    return toutesLesFetes.where((fete) =>
      fete.jour == date.day && fete.mois == date.month
    ).toList();
  }

  static List<Fete> getFetesDuMois(int mois) {
    return toutesLesFetes.where((fete) => fete.mois == mois).toList();
  }

  static Fete? getFeteDuSaintJoseph() {
    try {
      return toutesLesFetes.firstWhere((fete) =>
        fete.saintDuJour == 'Joseph'
      );
    } catch (e) {
      return null;
    }
  }
}